In [6]:
# Basic Q-learning algorithm
# src: http://mnemstudio.org/path-finding-q-learning-tutorial.htm
# e.g.: http://firsttimeprogrammer.blogspot.com/2016/09/getting-ai-smarter-with-q-learning.html

In [2]:
import numpy as np

In [3]:
# Define the reward matrix R
# - R is a 6 x 6 matrix
# - rows are states, cols are actions
R = np.array([
    [-1, -1, -1, -1, 0, -1],
    [-1, -1, -1, 0, -1, 100],
    [-1, -1, -1, 0, -1, -1],
    [-1, 0, 0, -1, 0, -1],
    [0, -1, -1, 0, -1, 100],
    [-1, 0, -1, -1, 0, 100],
])
print('Reward matrix:')
print(R)
print()

# Define the value matrix Q
# - Q is a 6 x 6 matrix
# - rows are states, cols are actions
Q = np.array([
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0],
])
print('Value matrix:')
print(Q)
print()

# Define the gamma
gamma = 0.8

# Define the absorbing state
ABSORBING_STATE = 5

# Repeat for n episodes
n = 1000
print("Being episodes...")
for _ in range(n):
    # Choose a random current state
    s = np.random.choice(range(6))
    # Do while absorbing state not reached
    while True:
        # Gell all actions from current state
        action_set = [k for k in range(6) if R[s, k] != -1]
        # Choose a random action
        a = np.random.choice(action_set)
        # Next state
        s_nxt = a
        # Set of all actions from s_next
        action_set = [k for k in range(6) if R[s_nxt, k] != -1]
        # Choose the best action
        best_action = max(action_set, key=lambda _a: Q[s_nxt, _a])
        # Update the Q matrix
        Q[s, a] = R[s, a] + gamma*Q[s_nxt, best_action]
        # Update current state
        s = s_nxt
        if s == ABSORBING_STATE:
            break
print("Done training.")
print()

# End learning
print('Value matrix:')
print(Q)

Reward matrix:
[[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1   0  -1]
 [  0  -1  -1   0  -1 100]
 [ -1   0  -1  -1   0 100]]

Value matrix:
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

Being episodes...
Done training.

Value matrix:
[[  0   0   0   0 396   0]
 [  0   0   0 316   0 496]
 [  0   0   0 316   0   0]
 [  0 396 252   0 396   0]
 [316   0   0 316   0 496]
 [  0 396   0   0 396 496]]


In [7]:
def get_opt_path(s):
    steps = [str(s)]
    while True:
        s_nxt = Q[s].argmax()
        steps.append(str(s_nxt))
        s = s_nxt
        if s_nxt == ABSORBING_STATE:
            break
    print('Optimal path:', '-'.join(steps))

In [8]:
for s in range(6):
    get_opt_path(s)


Optimal path: 0-4-5
Optimal path: 1-5
Optimal path: 2-3-1-5
Optimal path: 3-1-5
Optimal path: 4-5
Optimal path: 5-5
